spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: marcin.lechowski2@gmail.com
    password: Kaermorchen1!
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
allegro:
  api-url: https://api.allegro.pl
  client-id: 197291b4a9d745de83e35067139fdecd
  client-secret: lZX7Jg8FJkeoxpMa1kYZrZB8Rv6jIc1mqofkaPTBTpYrw7wD6Js2RRo2qeiyUN0s
  access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvOmFwaTpiaWRzIl0sImFsbGVncm9fYXBpIjp0cnVlLCJpc3MiOiJodHRwczovL2FsbGVncm8ucGwiLCJleHAiOjE3MzYyNDAyODUsImp0aSI6ImY4ZTU2NDJkLTIwZDMtNDM1NS1iOWEwLTk3NGYxNjRlMGYwZCIsImNsaWVudF9pZCI6IjE5NzI5MWI0YTlkNzQ1ZGU4M2UzNTA2NzEzOWZkZWNkIn0.TDK_PSm235n-b16kUW6pvnSTVZ9PlUeWDj00q8r0OlGii3QtffDBjFvw_FnW9h08LBsg8JJhi1a7eiPVtzqFGE9o39dgygl3ccUiAlN2JO3oY-gFHc_lYKrztSpYvv_Q6x7SIAUkU5znHCZit8DQgI_zumHi2L5S4sFrJLRPEJNkkjlV-E76Lduy4MZRGh0Ep0W3kFkz4jkl_D9gudOB_pb4SWtnSvha6V8ZMOnlFevfEM_h64PxWzRdCdNmCFwZH_UoeJ86hUkOhMzaXw_jKGVWRzNNJo8hkgnUIFO52tNf5BLOtX_NGk8dpqEplErfSf-U4rOa18NCNqDC8ThXgQ